// <auto-generated />
namespace PetNet.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class webappPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(webappPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201904052310147_webappPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
